export const data = [
  {
    id: 0,
    name: "Shiba inu",
    description: `
    The Shiba Inu is a breed of hunting dog from Japan. A small-to-medium breed,
    it is the smallest of the six original and distinct spitz breeds of dog native to Japan.
    A small, alert, and agile dog that copes very well with mountainous terrain and hiking trails,
    the Shiba Inu was originally bred for hunting. It looks similar to and is often mistaken
    for other Japanese dog breeds such as the Akita Inu or Hokkaido, but the Shiba Inu is a different breed with a distinct blood line, temperament, and smaller size than other Japanese dog breeds.
    Appearance
    The Shiba's frame is compact with well-developed muscles.
    The Shiba Inu is double coated, with the outer coat being stiff and straight and the undercoat soft and thick.
    Fur is short and even on the fox-like face, ears, and legs.
    Guard hairs stand off the body and are about 4 to 5 cm (1+1⁄2 to 2 in) long at the withers.
    The purpose of the guard hairs is to protect their underlying skin and to repel rain or snow.
    Tail hair is slightly longer and stands open in a brush. Their tails are a defining characteristic and makes them stand apart from other dog breeds. Their tails help to protect them from the harsh winter weather. When they sleep, Shiba Inus curl up and use their tails to shield their face and nose in order to protect their sensitive areas from the cold.[citation needed] The cream color is considered a "major fault" by both the Japan Kennel Club and American Kennel Club.[6] It should never be intentionally bred in a show dog, as the required markings known as "urajiro"  are not visible; "Urajiro" literally translates to "underside white".[2] Conversely, a white (cream) coat is perfectly acceptable according to the British Kennel Club breed standard.
  The urajiro (cream to white ventral color) is required in the following areas on all coat colors: on the sides of the muzzle, on the cheeks, inside the ears, on the underjaw and upper throat inside of legs, on the abdomen, around the vent and the ventral side of the tail. On reds: commonly on the throat, forechest, and chest. On blacks and sesames: commonly as a triangular mark on both sides of the forechest.[8]
  History
  The Shiba Inu has been identified as a basal breed that predates the emergence of the modern breeds in the 19th century.
  Dogs with a similar appearance to the Shiba Inu were represented in dogū made during the prehistoric Jōmon period of Japanese history.[14]Originally,
  the Shiba Inu was bred to hunt and flush small game, such as birds and rabbit. Shiba lived in the mountainous areas of the Chūbu region.
  During the Meiji Restoration, western dog breeds were imported and crosses between these and native Japanese breeds became popular. From 1912 to 1926, almost no pure Shiba remained. From around 1928, hunters and intellectuals began to show interest in the protection of the remaining pure Shiba;[15] however, despite efforts to preserve the breed, the Shiba nearly became extinct during World War II[5] due to a combination of food shortage and a post-war distemper epidemic.[1] All subsequent dogs were bred from the only three surviving bloodlines.[16] These bloodlines were the Shinshu Shiba from Nagano Prefecture, the Mino Shiba from the former Mino Province in the south of present-day Gifu Prefecture, and the San'in Shiba from Tottori and Shimane Prefectures.[17]
  The Shinshu Shibas possessed a solid undercoat, with a dense layer of guard-hairs,
  and were small and red in color. The Mino Shibas tended to have thick, prick ears, and possessed a sickle tail, rather than the common curled tail found on most modern Shibas. The San'in Shibas were larger than most modern shibas, and tended to be black, without the common tan and white accents found on modern black-and-tan shibas.[17] When the study of Japanese dogs was formalized in the early and mid-20th century, these three strains were combined into one overall breed, the Shiba Inu.[17] The first Japanese breed standard for the Shiba, the Nippo Standard, was published in 1934. In December 1936, the Shiba Inu was recognized as a Natural Monument of Japan through the Cultural Properties Act, largely due to the efforts of Nippo (Nihon Ken Hozonkai), the Association for the Preservation of the Japanese Dog.[17][18]
  In 1954, an armed service family brought the first Shiba Inu to the United States.
  In 1979, the first recorded litter was born in the United States.
  The Shiba was recognized by the American Kennel Club in 1992 and added to the AKC Non-Sporting Group in 1993.[1][19]
  It is now primarily kept as a pet both in Japan and abroad. According to the American Kennel Club, the Shiba Inu is the number one companion dog in Japan.
  In the United States, the growing popularity of the Shiba Inu is evident as the American Kennel Club Registration Statistics ranked the breed in 44th place in 2016; a rise from 50th place in 2012.[21]
  Health
  Overall, the Shiba Inu is a healthy dog breed.
  Health conditions known to affect this breed are allergies, glaucoma, cataracts, hip dysplasia, entropion, and luxating patella.
  Periodic joint examinations are recommended throughout the dog's life. Eye tests should be performed yearly as eye problems can develop over time. By two years of age, Shiba Inus may be considered fully free from joint problems, if none have been discovered, since at this age the skeleton is fully developed.[citation needed] As with most dog breeds, Shibas should be walked or otherwise exercised daily.[26] Their average life expectancy is from 12 to 16 years. Exercise, especially daily walks, is preferred for this breed to live a long and healthy life.[16] The oldest known Shiba, Pusuke, died at age 26 in early December 2011. Pusuke was the oldest dog alive at the time and lived three years less than the world record for the longest living dog.
  Grooming
  These dogs are very clean, so grooming needs will likely be minimal.
  They naturally tend to hate to be wet or bathed, thus, it is very important to start accustomed when they are young. A Shiba Inu's coat is coarse; short to medium length with the outer coat being 2.5 to 3.2 cm (1 to 1+1⁄4 in) long, and is naturally waterproof so there is little need for regular bathing. They also have a thick undercoat that can protect them from temperatures well below freezing. However, shedding, also known as blowing coat, can be a nuisance. Shedding is heaviest during the seasonal change and particularly during the summer season, but daily brushing can temper this problem. It is recommended that owners never shave or cut the coat of a Shiba Inu, as the coat is needed to protect them from both cold and hot temperatures.[27]
  `,
    img: "https://images.loox.io/uploads/assets/code-assignment/shiba_inu.jpeg"
  },
  {
    id: 1,
    name: "Fennec",
    description: `

    The fennec fox (Vulpes zerda) is a small crepuscular fox native to the Sahara Desert,
    the Sinai Peninsula in Egypt, and the Arava and Negev deserts in Israel.
    Its most distinctive feature is its unusually large ears,
    which serve to dissipate heat. The fennec is the smallest canid species.
    Its coat, ears, and kidney functions have adapted to the desert environment with high temperatures and little water. Also, its hearing is sensitive to hear prey moving underground. It mainly eats insects, small mammals, and birds. The fennec has a life span of up to 14 years in captivity and about 10 years in the wild. Its main predators are the Verreaux's eagle-owl, jackals, and other large mammals. Fennec families dig out burrows in the sand for habitation and protection, which can be as large as 120 m2 (1,292 sq ft) and adjoin the burrows of other families. Precise population figures are not known but are estimated from the frequency of sightings; these indicate that the fennec is currently not threatened by extinction. Knowledge of social interactions is limited to information gathered from captive animals. The fennec's fur is prized by the indigenous peoples of North Africa,
    and in some parts of the world, it is considered an exotic pet.
    Description
    The fur of the fennec fox is straw-
    coloured. Its nose is black. Its tapering tail has a black tip. Its long ears have longitudinal reddish stripes on the back and are so densely haired inside that the external auditory meatus is not visible.[6] The edges of the ears are whitish, but darker on the back. The ear to body ratio is greatest in the canid family and likely help in dissipating heat and locating vertebrates. It has dark streaks running from the inner eye to either side of the slender muzzle. Its large eyes are dark.
  The fennec fox is the smallest canid. Females range in head-to-body size from 34.5 to 39.5 cm (13.6 to 15.6 in) with a 23–25 cm (9.1–9.8 in) long tail and 9–9.5 cm (3.5–3.7 in) long ears, and weigh 1–1.9 kg (2.2–4.2 lb). Males are slightly larger, ranging in head-to-body size from 39 to 39.5 cm (15.4 to 15.6 in) with a 23–25 cm (9.1–9.8 in) long tail and 10 cm (3.9 in) long ears, weighing at least 1.3 kg (2.9 lb).[10]
  Behaviour and ecology
  A fennec fox digs its den in sand,
  either in open areas or places sheltered by plants with stable sand dunes. In compacted soils, dens are up to 120 m2 (1,300 sq ft) large, with up to 15 different entrances. In some cases, different families interconnect their dens, or locate them close together. In soft, looser sand, dens tend to be simpler with only one entrance leading to a single chamber.[10]
  Hunting and diet
  The fennec fox is an omnivore, feeding on small rodents,
  lizards, geckos, skinks, small birds and their eggs, fruits and also some tubers. It relies on the moisture content of prey, but drinks water when available.[10] It hunts alone and digs in the sand for small vertebrates and insects. Some individuals were observed to bury prey for later consumption and searching for food in the vicinity of human settlements.[12] In the Algerian Sahara, 114 scat samples were collected that contained more than 400 insects, plant fragments and date palm Phoenix dactylifera fruits, remains of birds, mammals, squamata and insects.[13]
  Reproduction
  Captive fennec foxes reach sexual maturity at around nine months
  and mate between January and April.[14][15] They usually breed only once per year. The copulation tie lasts up to two hours and 45 minutes.[16] Gestation lasts between 50 and 52 days,
  sometimes also up to 63 days.[17][18] After mating, the male becomes very aggressive and protects the female, provides her with food during pregnancy and lactation.[19] Females give birth between March and June to a litter of one to four pups that open their eyes after 8 to 11 days.[18][15] Both female and male care for the pups. They communicate by barking, purring, yapping and squeaking. Pups remain in the family even after a new litter is born.[14] The pups are weaned at the age of 61 to 70 days.[20] The oldest captive male fennec fox was 14 years old, and the oldest female 13 years.[10]
  Predators
  African horned owl species likely prey on fennec fox pups. Anecdotal reports exist about caracals, jackals, and striped hyenas also preying on the fennec fox. But according to nomads, the fennec fox is fast and changes directions so that even their Salukis are hardly able to capture it.[10]
  `,
    img: "https://images.loox.io/uploads/assets/code-assignment/fennec.jpeg"
  },
  {
    id: 2,
    name: "Genet",
    description: `
    The common genet has a slender, cat-like body,
    a small head with a pointed muzzle, large oval ears,
    large eyes and well-developed whiskers up to 7 cm (2.8 in)
    in length. Its legs are short, with cat-like feet and semi-retractile claws. Its fur is dense and soft, and the coat is pale grey, with numerous black markings. The back and flanks are marked with about five rows of black spots,
    and a long black stripe runs along the middle of the back from the shoulders to the rump. There is also a black stripe on the forehead, and dark patches beneath the eyes, which are offset against the white fur of the chin and throat. The tail is striped, with anything from eight to thirteen rings along its length. Its body is 43 to 55 cm (17 to 22 in) long with a 33 to 52 cm (13 to 20 in) long tail. Males weigh an average of 2 kg (4.4 lb) and are about 10% larger than females.[3] It has an erectile crest of hair from the shoulder to the base of the tail, a white tail tip and black hind feet.
  The common genet is solitary.
  Adults are nocturnal and crepuscular, with their highest levels of activity following sunset and just prior to sunrise; juveniles may be active during the day. They rest during the day in hollow trees or among thickets, and frequently use the same resting sites. In southern Spain, adult individuals occupy home ranges of about 7.8 km2 (3.0 sq mi) in average. The ranges of males and females overlap, but those of members of the same sex do not.[19] In northern Spain, home ranges of three females ranged from 2.1 to 10.2 km2 (0.81 to 3.94 sq mi).
  During a study in northeastern Spain, males have been found to be more active than females at night because of their greater size, which indicates that males have greater energy requirements to satisfy their physiological needs. Females typically weigh less, and they have been found to be less active overall. Females' home ranges are also smaller than those of males.[21] Males had a mean annual home range of 113 ha (280 acres), and females of 72 ha (180 acres). While males have larger home ranges in all seasons, the differences between males' and females' territories are most significant during the winter. Their home ranges are slightly larger during the spring because they are more active, not only nocturnally, but in seeking a mate. Because of their increased activity, they require more energy and are more active to acquire the necessary sustenance.[22]
  Both male and females scent mark in their home ranges.
  Females mark their territory using scent glands on their flanks, hind legs, and perineum. Males mark less frequently than females, often spraying urine, rather than using their scent glands, and do so primarily during the breeding season. Scent marks by both sexes allow individuals to identify the reproductive and social status of other genets. Common genets also defecate at specific latrine sites, which are often located at the edge of their territories, and perform a similar function to other scent marks.[3]
  Five communication calls have been reported.
  The hiccup call is used by males during the mating period and by females to call the litter. Kits purr during their first week of life and, during their dependent weeks, moan or mew. Kits also growl after the complete development of predatory behavior and during aggressive interactions. Finally, genets utter a "click" as a threat. Threatening behavior consists of erection of the dark central dorsal band of hair, an arched-back stance, opening the mouth, and baring the teeth.[3]
  The common genet uses five distinct calls.
  The "hiccup" call is used to indicate friendly interactions, such as between a mother and her young, or between males and females prior to mating. Conversely, clicks, or, in younger individuals, growls, are used to indicate aggression. The remaining two calls, a "mew" and a purr, are used only by young still dependent on their mother.[3]
  It has a varied diet comprising small mammals, lizards, birds, bird eggs, amphibians, centipedes, millipedes, scorpions, insects and fruit, including figs and olives. The wood mouse is a favourite prey item,[23] It also prey on red squirrels (Sciurus vulgaris) and dormice (Eliomys quercinus).[citation needed] Genets locate their prey primarily by scent, and kill with a bite to the neck, like cats. Small rodents are captured by the back and killed with a bite at the head, then eaten starting with the head.[3][24]
  In Spain, common genets can suffer from infestation of parasitic helminths, as well as ticks, fleas[verification needed] (Hippobosca)[verification needed], and lice.
  Common genets also host the phthirapteran Eutrichophilus genettae and Lorisicola (Paradoxuroecus) genettae.[25]
  In Africa, predators include leopard, serval, caracal, ratel and large owl species.[26] Potential predators are also red fox and northern goshawk.
  `,
    img: "https://images.loox.io/uploads/assets/code-assignment/genet.jpeg"
  },
  {
    id: 3,
    name: "Elk",
    description: `
    The elk (Cervus canadensis), also known as the wapiti, is one of the largest species within the deer family, Cervidae, and one of the largest terrestrial mammals in North America, as well as Central and East Asia. It is often confused with the larger Alces alces, which is called moose in North America, but called elk in British English, and related names in other European languages (German Elch, Swedish älg, French élan). The name "wapiti" is used in Europe for Cervus canadensis. It originates from the Shawnee and Cree word waapiti, meaning 'white rump'.
    Elk range in forest and forest-edge habitat, feeding on grasses, plants, leaves, and bark. Male elk have large antlers which they shed each year. Males also engage in ritualized mating behaviors during the rut, including posturing, antler wrestling (sparring), and bugling, a loud series of vocalizations that establishes dominance over other males and attracts females.
    Although it is currently native to North America and eastern Asia, it had a much wider distribution in the past. Populations were present across Eurasia into Western Europe during the Late Pleistocene and survived into the early Holocene in southern Sweden and the Alps. The elk has adapted well to countries where it has been introduced, including Argentina and New Zealand. Its adaptability may in fact threaten endemic species and the ecosystems into which it has been introduced.
    Elk are susceptible to a number of infectious diseases, some of which can be transmitted to livestock. Efforts to eliminate infectious diseases from elk populations, largely by vaccination, have had mixed success. Some cultures revere the elk as having spiritual significance. In parts of Asia, antlers and their velvet are used in traditional medicines. Elk are hunted as a game species. Their meat is leaner and higher in protein than beef or chicken. Elk were long believed to belong to a subspecies of the European red deer (Cervus elaphus), but evidence from many mitochondrial DNA genetic studies beginning in 1998 shows that the two are distinct species. Key morphological differences that distinguish C. canadensis from C. elaphus are the former's wider rump patch and paler-hued antlers.
    Naming and etymology
    By the 17th century, Alces alces (called "elk" in Europe) had long been extirpated from the British Isles, and the meaning of the word "elk" to English-speakers became rather vague, acquiring a meaning similar to "large deer".[3] English-speaking people arriving in North America during the European colonization of the Americas lacked familiarity with Alces alces on either side of the Atlantic Ocean, but familiar with the smaller red deer (Cervus elaphus) of the British Isles, thought that the larger North American C. canadensis resembled the even larger Alces alces, and thus gave to it the name "elk".
  The name wapiti is from the Shawnee and Cree word waapiti, meaning "white rump".[4] There is a subspecies of wapiti in Mongolia called the Altai wapiti (Cervus canadensis sibiricus), also known as the Altai maral.[5] The Asian subspecies are sometimes referred to as the maral, but this name applies primarily to the Caspian red deer (Cervus elaphus maral), a subspecies of red deer.
  According to the Oxford English Dictionary, the etymology of the word "elk" is "of obscure history".[6] In Classical Antiquity, the European Alces alces was known as Ancient Greek: ἄλκη, romanized: álkē and Latin: alces, words probably borrowed from a Germanic language or another language of northern Europe.[6] By the 8th century, during the Early Middle Ages, the moose was known as Old English: elch, elh, eolh, derived from the Proto-Germanic: *elho-, *elhon- and possibly connected with the Old Norse: elgr.[6] Later, the species became known in Middle English as elk, elcke, or elke, appearing in the Latinized form alke, with the spelling alce borrowed directly from Latin: alces.[6][7] Noting that elk "is not the normal phonetic representative" of the Old English elch, the Oxford English Dictionary derives elk from Middle High German: elch, itself from Old High German: elaho.[6][3]
  The American Cervus canadensis was recognized as a relative of the red deer (Cervus elaphus), of Europe, and so Cervus canadensis was referred to as "red deer".[8] Richard Hakluyt, in his 1584 Discourse Concerning Western Planting, mentioned the continent's plentiful red deer (Early Modern English: greate store of ... redd dere).[8] Similarly, John Smith's 1616 A Description of New England referred to red deer.[8] Sir William Talbot's 1672 English translation of John Lederer's Latin Discoveries likewise called the species "Red Deer", but noted in parentheses that they were "for their unusual largeness improperly termed Elks by ignorant people".[8] Both Thomas Jefferson's 1785 Notes on the State of Virginia and David Bailie Warden's 1816 Statistical, Political, and Historical Account of the United States used "red deer" to refer to Cervus canadensis.[8]
  Taxonomy
  Members of the genus Cervus (and hence early relatives or possible ancestors of the elk) first appear in the fossil record 25 million years ago, during the Oligocene in Eurasia, but do not appear in the North American fossil record until the early Miocene.[9] The extinct Irish elk (Megaloceros) was not a member of the genus Cervus but rather the largest member of the wider deer family (Cervidae) known from the fossil record.[10]
  Until recently, red deer and elk were considered to be one species, Cervus elaphus,[5][11] with over a dozen subspecies. But mitochondrial DNA studies conducted in 2004 on hundreds of samples from red deer and elk subspecies and other species of the Cervus deer family, strongly indicate that elk, or wapiti, should be a distinct species, namely Cervus canadensis.[12] DNA evidence validates that elk are more closely related to Thorold's deer and even sika deer than they are to the red deer.[12]
  Elk and red deer produce fertile offspring in captivity, and the two species have freely inter-bred in New Zealand's Fiordland National Park. The cross-bred animals have resulted in the disappearance of virtually all pure elk blood from the area.[13] Key morphological differences that distinguish C. canadensis from C. elaphus are the former's wider rump patch and paler-hued antlers.[14]
  Subspecies
  There are numerous subspecies of elk described, with six from North America and four from Asia, although some taxonomists consider them different ecotypes or races of the same species (adapted to local environments through minor changes in appearance and behavior). Populations vary in antler shape and size, body size, coloration and mating behavior. DNA investigations of the Eurasian subspecies revealed that phenotypic variation in antlers, mane and rump patch development are based on "climatic-related lifestyle factors".[15] Of the six subspecies of elk known to have inhabited North America in historical times, four remain, including the Roosevelt's (C. canadensis roosevelti), tule (C. canadensis nannodes), Manitoban (C. canadensis manitobensis) and Rocky Mountain elk (C. canadensis nelsoni).[16] The eastern elk (C. canadensis canadensis) and Merriam's elk (C. canadensis merriami) subspecies have been extinct for at least a century.[17][18]
  Four subspecies described in Asia include the Altai wapiti (C. canadensis sibiricus) and the Tianshan wapiti (C. canadensis songaricus). Two distinct subspecies found in China, Mongolia, the Korean Peninsula[19] and Siberia are the Manchurian wapiti (C. canadensis xanthopygus) and the Alashan wapitis (C. canadensis alashanicus). The Manchurian wapiti is darker and more reddish in coloration than the other populations. The Alashan wapiti of north central China is the smallest of all subspecies, has the lightest coloration and is the least studied.[13]
  Recent DNA studies suggest that there are no more than three or four subspecies of elk. All American forms, aside from possibly the tule and Roosevelt's elk, seem to belong to one subspecies (Cervus canadensis canadensis). Even the Siberian elk (Cervus canadensis sibiricus) are more or less identical to the American forms and therefore may belong to this subspecies, too. However, the Manchurian wapiti (Cervus canadensis xanthopygus) is clearly distinct from the Siberian forms, but not distinguishable from the Alashan wapiti. The Chinese forms the Sichuan deer, Kansu red deer, and Tibetan red deer belong also to the wapitis and were not distinguishable from each other by mitochondrial DNA studies.[12] These Chinese subspecies are sometimes treated as a distinct species, namely the Central Asian red deer (Cervus wallichi), which also includes the Kashmir stag.[20]
  Characteristics
  Elk have thick bodies with slender legs and short tails. They have a shoulder height of 0.75–1.5 m (2 ft 6 in–4 ft 11 in) with a nose-to-tail length of 1.6–2.7 m (5 ft 3 in–8 ft 10 in). Males are larger and weigh 178–497 kg (392–1,096 lb) while females weigh 171–292 kg (377–644 lb).[21] The largest of the subspecies is the Roosevelt elk (C. c. roosevelti), found west of the Cascade Range in the U.S. states of California, Oregon and Washington, and in the Canadian province of British Columbia. Roosevelt elk have been reintroduced into Alaska, where the largest males are estimated to weigh up to 600 kg (1,300 lb).[22] More typically, male Roosevelt elk weigh around 318 to 499 kg (701 to 1,100 lb), while females weigh 261 to 283 kg (575 to 624 lb).[23] Male tule elk weigh 204–318 kg (450–701 lb) while females weigh 170–191 kg (375–421 lb).[24]
  Antlers are made of bone, which can grow at a rate of 2.5 centimeters (0.98 in) per day. While actively growing, a soft layer of highly vascularized skin known as velvet covers and protects them. This is shed in the summer when the antlers have fully developed.[25] Bull elk typically have around six tines on each antler. The Siberian and North American elk carry the largest antlers while the Altai wapiti has the smallest.[13] Roosevelt bull antlers can weigh 18 kg (40 lb).[25] The formation and retention of antlers are testosterone-driven.[26] In late winter and early spring, the testosterone level drops, which causes the antlers to shed.[27]
  During the fall, elk grow a thicker coat of hair, which helps to insulate them during the winter.[28] Both male and female North American elk grow thin neck manes; females of other subspecies may not.[29]:37 By early summer, the heavy winter coat has been shed. Elk are known to rub against trees and other objects to help remove hair from their bodies. All elk have small and clearly defined rump patches with short tails. They have different coloration based on the seasons and types of habitats, with gray or lighter coloration prevalent in the winter and a more reddish, darker coat in the summer. Subspecies living in arid climates tend to have lighter colored coats than do those living in forests.[28] Most have lighter yellow-brown to orange-brown coats in contrast to dark brown hair on the head, neck, and legs during the summer. Forest-adapted Manchurian and Alashan wapitis have red or reddish-brown coats with less contrast between the body coat and the rest of the body during the summer months. Calves are born spotted, as is common with many deer species, and lose them by the end of summer. Adult Manchurian wapiti may retain a few orange spots on the back of their summer coats until they are older. This characteristic has also been observed in the forest-adapted European red deer.[13
    Behavior and ecology
    Elk are among the most gregarious deer species.[29]:52 During the summer group size can reach 400 individuals.[21] For most of the year, adult males and females are segregated into different herds. Female herds are larger while bulls form small groups and may even travel alone. Young bulls may associate with older bulls or female groups. Male and female herds come together during the mating season, which may begin in late August.[29]:75, 82 During this time, bulls enter the rut and compete for females to include in their harems.[29]:92 Males try to intimidate rivals by vocalizing and displaying with their antlers.[29]:109 If neither bull backs down, they engage in antler wrestling, sometimes sustaining serious injuries.[30] Bulls also dig holes in the ground called wallows, in which they urinate and roll their bodies.[31][30] A male elk's urethra points upward so that urine is sprayed almost at a right angle to the penis.[32] The urine soaks into their hair and gives them a distinct smell which attracts cows.[30]
    Dominant bulls follow groups of cows during the rut from August into early winter. A bull will defend his harem of 20 cows or more from competing bulls and predators.[33] A bull interacts with cows in his harem in two ways: herding and courtship. When a female wanders too far away from the harem's range, the male will rush ahead of her, block her path and aggressively rush her back to the harem. Herding behavior is accompanied a stretched out and lowered neck and the antlers laid back. A bull may get violent and hit the cow with his antlers. During courtship, the bull is more peaceful and approaches her with his head and antlers raised. The male signals his intention to test the female for sexual receptivity by flicking his tongue. If not ready, a cow will lower her head and weave from side to side while opening and closing her mouth. The bull will stop in response in order not to scare her.[29]:100–101 Otherwise, the bull will copiously lick the female and then mount her.[29]:115
    Younger, less dominant bulls, known as "spike bulls" because their antlers have not yet forked, will harass unguarded cows. These bulls are impatient and will not perform any courtship rituals and will continue to pursue a female even when she signals him to stop. As such, they are less reproductively successful, and a cow may stay close to the big bull to avoid harassment. Dominant bulls are intolerant of spike bulls and will chase them away from their harems.[29]:100–105
    Bulls have a loud, high-pitched, whistle-like vocalization known as bugling, which advertise the male's fitness over great distances. Unusual for a vocalization produced by a large animal, buglings can reach a frequency of 4000 Hz. This is achieved by blowing air from the glottis through the nasal cavities. Elk can produce deeper pitched (150 Hz) sounds using the larynx.[34]
    Reproduction and lifecycle
    Female elk have a short estrus cycle of only a day or two, and matings usually involve a dozen or more attempts. By the autumn of their second year, females can produce one and, very rarely, two offspring. Reproduction is most common when cows weigh at least 200 kilograms (440 lb).[35] The gestation period is 240 to 262 days and the offspring weigh between 15 and 16 kilograms (33 and 35 lb). When the females are near to giving birth, they tend to isolate themselves from the main herd, and will remain isolated until the calf is large enough to escape predators.[30]
    Calves are born spotted, as is common with many deer species, and they lose their spots by the end of summer. After two weeks, calves are able to join the herd, and are fully weaned at two months of age.[21] Elk calves are as large as an adult white-tailed deer by the time they are six months old.[36] Elk will leave their natal (birth) ranges before they are three years old. Males disperse more often than females, as adult cows are more tolerant of female offspring from previous years.[37] Elk live 20 years or more in captivity but average 10 to 13 years in the wild. In some subspecies that suffer less predation, they may live an average of 15 years in the wild.[38]
    Migration
    As is true for many species of deer, especially those in mountainous regions, elk migrate into areas of higher altitude in the spring, following the retreating snows, and the opposite direction in the fall. Hunting pressure impacts migration and movement.[39] During the winter, they favor wooded areas for the greater availability of food to eat. Elk do not appear to benefit from thermal cover.[40] The Greater Yellowstone Ecosystem elk herds comprise as many as 40,000 individuals.[41] During the spring and fall, they take part in the longest elk migration in the continental U.S., traveling as much as 168 mi (270 km) between summer and winter ranges.[42] The Teton herd consists of between 9,000 and 13,000 elk and they spend winters on the National Elk Refuge, having migrated south from the southern portions of Yellowstone National Park and west from the Shoshone and Bridger–Teton National Forests.[42]
    Diet
    Elk are ruminants and therefore have four-chambered stomachs. Unlike white-tailed deer and moose, which are chiefly browsers, elk are similar to cattle in that they are primarily grazers. But like other deer, they also browse.[43][44] Elk have a tendency to do most of their feeding in the mornings and evenings, seeking sheltered areas in between feedings to digest. Their diets vary somewhat depending on the season, with native grasses being a year-round supplement, tree bark being consumed in winter, and forbs and tree sprouts during the summer. Elk consume an average of 9.1 kilograms (20 lb) of vegetation daily.[45] Particularly fond of aspen sprouts which rise in the spring, elk have had some impact on aspen groves which have been declining in some regions where elk exist.[46] Range and wildlife managers conduct surveys of elk pellet groups to monitor populations and resource use.[47][48]
    Predators and defensive tactics
    Single bull elk in winter are vulnerable to predation by wolves.
    Predators of elk include wolves, coyotes, brown and black bears, cougars, and Siberian tigers.[49][50] Coyote packs mostly prey on elk calves, though they can sometimes take a winter- or disease-weakened adult.[51] In the Greater Yellowstone Ecosystem, which includes Yellowstone National Park, bears are the most significant predators of calves[52] while healthy bulls have never been recorded to be killed by bears and such encounters can be fatal for bears.[53] The killing of cows in their prime is more likely to affect population growth than the killing of bulls or calves.[54]
    Elk may avoid predation by switching from grazing to browsing. Grazing puts an elk in the compromising situation of being in an open area with its head down, leaving it unable to see what is going on in the surrounding area.[55] Living in groups also lessens the risk of an individual falling to predation. Large bull elk are less vulnerable and can afford to wander alone, while cows stay in larger groups for protection for their calves.[29]:75 Bulls are more vulnerable to predation by wolves in late winter, after they have been weakened by months of chasing females and fighting.[54] Males that have recently lost their antlers are more likely to be preyed upon.[56]
    Parasites and disease
    At least 53 species of protist and animal parasites have been identified in elk.[57] Most of these parasites seldom lead to significant mortality among wild or captive elk. Parelaphostrongylus tenuis (brainworm or meningeal worm) is a parasitic nematode known to affect the spinal cord and brain tissue of elk and other species, leading to death.[58] The definitive host is the white-tailed deer, in which it normally has no ill effects. Snails and slugs, the intermediate hosts, can be inadvertently consumed by elk during grazing.[59] The liver fluke Fascioloides magna and the nematode Dictyocaulus viviparus are also commonly found parasites that can be fatal to elk.[60] Since infection by either of these parasites can be lethal to some commercial livestock species, their presence in elk herds is of some concern.
    A bull elk in spring, shedding its winter coat and with its antlers covered in velvet
    Chronic wasting disease, transmitted by a misfolded protein known as a prion, affects the brain tissue in elk, and has been detected throughout their range in North America. First documented in the late 1960s in mule deer, the disease has affected elk on game farms and in the wild in a number of regions. Elk that have contracted the disease begin to show weight loss, changes in behavior, increased watering needs, excessive salivation and urinating and difficulty swallowing, and at an advanced stage, the disease leads to death. No risks to humans have been documented, nor has the disease been demonstrated to pose a threat to domesticated cattle.[61] In 2002, South Korea banned the importation of elk antler velvet due to concerns about chronic wasting disease.[62]
    The Gram-negative bacterial disease brucellosis occasionally affects elk in the Greater Yellowstone Ecosystem, the only place in the U.S. where the disease is still known to exist. In domesticated cattle, brucellosis causes infertility, abortions, and reduced milk production. It is transmitted to humans as undulant fever, producing influenza-like symptoms that may last for years. Though bison are more likely to transmit the disease to other animals, elk inadvertently transmitted brucellosis to horses in Wyoming and cattle in Idaho. Researchers are attempting to eradicate the disease through vaccinations and herd-management measures, which are expected to be successful.[63] Nevertheless, research has been ongoing since 2002, and a successful vaccine has yet to be developed as of 2016.[64]
    A recent necropsy study of captive elk in Pennsylvania attributed the cause of death in 33 of 65 cases to either gastrointestinal parasites (21 cases, primarily Eimeria sp. and Ostertagia sp.) or bacterial infections (12 cases, mostly pneumonia).[65]
    Elk hoof disease was first noticed in the state of Washington in the late 1990s in the Cowlitz River basin, with sporadic reports of deformed hooves. Since then, the disease has spread rapidly with increased sightings throughout southwest Washington and into Oregon. The disease is characterised by deformed, broken, or missing hooves and leads to severe lameness in elk. The primary cause is not known, but it is associated with treponeme bacteria, which are known to cause digital dermatitis in commercial livestock. The mode of transmission is also not known, but it appears to be highly contagious among elk. Studies are being undertaken by government departments to determine how to halt or eliminate the disease.[66][67][68]
    `,
    img: "https://images.loox.io/uploads/assets/code-assignment/Elk.jpeg"
  },
  {
    id: 4,
    name: "Portuguese man o' war",
    description: `
      The Portuguese man o' war (Physalia physalis), also known as the man-of-war,
      bluebottle, blue bottle jellyfish,
      or floating terror is a marine hydrozoan found in the Atlantic Ocean and the Indian Ocean. It is considered to be the same species as the Pacific man o' war, which is found mainly in the Pacific Ocean.
      The Portuguese man o' war is the only species in the genus Physalia, which in turn is the only genus in the family Physaliidae.
      It has numerous venomous microscopic nematocysts which deliver a painful sting powerful enough to kill fish, and has been known to occasionally kill humans. Although it superficially resembles a jellyfish, the Portuguese man o' war is in fact a siphonophore. Like all siphonophores, it is a colonial organism, made up of many smaller units called zooids.[9] All zooids in a colony are genetically identical, but fulfill specialized functions such as feeding and reproduction, and together allow the colony to operate as a single individual.
      Habitat
      Found mostly in tropical and subtropical waters,[12][13] the Portuguese man o' war lives at the surface of the ocean. The gas-filled bladder, or pneumatophore, remains at the surface, while the remainder is submerged.[14] Portuguese men o' war have no means of propulsion, and move passively, driven by the winds, currents, and tides.
    Strong winds may drive them into bays or onto beaches. Often, finding a single Portuguese man o' war is followed by finding many others in the vicinity.[15] Because they can sting while beached, the discovery of a man o' war washed up on a beach may lead to the closure of the beach.[16][17]
    Anatomy and physiology
    Just like all siphonophores, the Portuguese man o' war is colonial: each man o' war is composed of many smaller units (zooids) that hang in clusters from under a large, gas-filled structure called the pneumatophore.[18] New zooids are added by budding as the colony grows. As many as seven different kinds of zooids have been described in the man o' war: three of the medusoid type (gonophores, nectophores, and vestigial nectophores) and four of the polypoid type (free gastrozooids, tentacle-bearing zooids, gonozooids and gonopalpons).[19] However, naming and categorization of zooids varies between authors, and much of the embryonic and evolutionary relationships of zooids remains unclear.[9] The pneumatophore, or bladder, is the most conspicuous part of the man o' war. It is translucent and tinged blue, purple, pink, or mauve, and may be 9 to 30 centimetres (3.5 to 11.8 inches) long and rise as high as 15 cm (6 in) above the water. The pneumatophore functions as both a flotation device and a sail for the colony, allowing the colony to move with the prevailing wind.[9][18] The gas in the pneumatophore is part carbon monoxide (0.5–13%), which is actively produced by the animal, and part atmospheric gases (nitrogen, oxygen and noble gases) that diffuse in from the surrounding air.[20] In the event of a surface attack, the pneumatophore can be deflated, allowing the colony to temporarily submerge.[21] The colony hunts and feeds through the cooperation of two types of zoo"id": gastrozooids and tentacle-bearing zooids known as dactylozooids[9] or tentacular palpons. The dactylozooids are equipped with tentacles, which are typically about 10 m (30 ft) in length but can reach over 30 m (100 ft).[15][22] Each tentacle bears tiny, coiled, thread-like structures called nematocysts. Nematocysts trigger and inject venom on contact, stinging, paralyzing, and killing adult or larval squids and fishes. Large groups of Portuguese man o' war, sometimes over 1,000 individuals, may deplete fisheries.[19][21] Contraction of tentacles drags the prey upward, into range of the gastrozooids, the digestive zooids. The gastrozooids surround and digest the food by secreting enzymes. The main reproductive zooids, the gonophores, are situated on branching structures called gonodendra. Gonophores produce sperm or eggs (see life cycle). Besides gonophores, each gonodendron also contains several other types of specialized zooids: gonozooids (which are accessory gastrozooids), nectophores (which have been speculated to allow detached gonodendra to swim), and vestigial nectophores (also called jelly polyps; the function of these is unclear).[9]
    Coloniality
    The man o' war is described as a colonial organism because the individual zooids in a colony are evolutionarily derived from either polyps or medusae,[23] i.e. the two basic body plans of cnidarians.[24] Both of these body plans comprise entire individuals in non-colonial cnidarians (for example, a jellyfish is a medusa; a sea anemone is a polyp). All zooids in a man o' war develop from the same single fertilized egg and are therefore genetically identical; they remain physiologically connected throughout life, and essentially function as organs in a shared body. Hence, a Portuguese man o' war constitutes a single individual from an ecological perspective, but is made up of many individuals from an embryological perspective.[23]
    Left- or right-handedness
    A Portuguese man o' war is somewhat asymmetrically shaped: the zooids of the colony hang down not quite from the midline of the pneumatophore, but offset to either the right or left side of the midline. When combined with the trailing action of the tentacles (which function as a sea anchor), this left- or right-handedness makes the colony sail sideways relative to the wind, by about 45° in either direction.[25][26] Colony handedness has therefore been theorized to affect man o' war migration, with left-handed or right-handed colonies potentially being more likely to drift down particular respective sea routes.[25] While previously believed to develop as a result of what winds a colony experienced, handedness in fact emerges early in the colony's life, while it is still living below the surface of the sea.[9]
    Venom
    This species is responsible for up to 10,000 human stings in Australia each summer, particularly on the east coast, with some others occurring off the coast of South Australia and Western Australia.[27] The stinging, venom-filled nematocysts in the tentacles of the Portuguese man o' war can paralyze small fish and other prey.[28] Detached tentacles and dead specimens (including those that wash up on shore) can sting just as painfully as the live organism in the water, and may remain potent for hours or even days after the death of the organism or the detachment of the tentacle.[29] Stings usually cause severe pain to humans, leaving whip-like, red welts on the skin that normally last two or three days after the initial sting, though the pain should subside after about 1 to 3 hours (depending on the biology of the person stung). However, the venom can travel to the lymph nodes and may cause symptoms that mimic an allergic reaction, including swelling of the larynx, airway blockage, cardiac distress, and an inability to breathe. Other symptoms can include fever and shock, and in some extreme cases, even death,[30] although this is extremely rare. Medical attention for those exposed to large numbers of tentacles may become necessary to relieve pain or open airways if the pain becomes excruciating or lasts for more than three hours, or if breathing becomes difficult. Instances where the stings completely surround the trunk of a young child are among those that have the potential to be fatal.[31]

    Treatment of stings
    Stings from a Portuguese man o' war are often extremely painful. They result in severe dermatitis characterized by long, thin, open wounds that resemble those caused by a whip.[32] These are not caused by any impact or cutting action, but by irritating urticariogenic substances in the tentacles.[33][34] Flushing the affected area with sea water helps remove any adherent tentacles in the wound area.[31][35][36][37] Acetic acid (vinegar) or a solution of ammonia and water is popularly believed to deactivate the remaining nematocysts and usually provides some pain relief,[31] though some isolated studies suggest that in some individuals vinegar dousing may increase toxin delivery and worsen symptoms.[35][38] Vinegar has also been claimed to provoke hemorrhaging when used on the less severe stings of cnidocytes of smaller species.[39] The current recommended treatment from studies in Australia is to avoid the use of vinegar, as local studies have shown this to exacerbate the symptoms.
    The ammonia soak is then often followed by the application of shaving cream to the wound for 30 seconds, followed by shaving the area with a razor and rinsing the razor thoroughly between each stroke. This removes any remaining unfired nematocysts. Heat in the form of hot saltwater or hot packs may be applied: heat speeds the breakdown of the toxins already in the skin. Hydrocortisone cream may also be used.[31]
    A 2017 study stated that a wash of undiluted vinegar or Sting No More Spray, a proprietary "combined stinging capsule and venom-inhibiting product" were the most effective topical rinse solutions.[40] The vinegar (or spray) rinse should be followed by immersion in 45°C (113°F) water or application of a hot pack for 45 minutes.[41]

    `,
    img: "https://images.loox.io/uploads/assets/code-assignment/Portuguese_man_o_war.jpeg"
  }
];
